### ISSUE TITLE
?

### ISSUE THREAD

**Issue by mika32154** [Razmoth/MiHoYoAssets#2]
Is this command wrong? MiHoYoAssets format [CB1] C:\Users\Owner\Downloads\Genshin Impact CBT 1\Genshin Impact CBT 1\GS_Data\StreamingAssets\AssetBundles C:\Users\Owner\Downloads\Genshin Impact CBT 1 when i run it it just tells me how to use it and im confused

**Comment by Modder4869** [comment]
no need to add [ ] just type CB1

**Comment by mika32154** [comment]
![unknown](https://user-images.githubusercontent.com/96961915/182279415-caeeda03-9f73-446a-92e1-800696ae0004.png)
it still tells me the same heres a pic

**Comment by Modder4869** [comment]
try quoting the path like "folderpath"

**Comment by mika32154** [comment]
tysm that worked! :)
